PUT http://localhost:3003/api/blogs/5e96f52f4cde1f5357792ee0
Content-Type: application/json

{
    "title": "Blog1",
    "author": "Author of update",
    "url": "http://www.example.com",
    "likes": 12
}